---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana
  package: name=kibana state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- name: Create logging directory
  file:
    path: "{{ kibana_log_dir }}"
    state: directory
    mode: 0755
    owner: kibana
    group: kibana
  when: kibana_log_dir is defined

- name: Copy Kibana configuration from role's template
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    owner: kibana
    group: kibana
    mode: 0644
  notify: restart kibana
  when: kibana_conf_template is not defined

- name: Copy Kibana configuration template from playbook
  template:
    src:  "{{ playbook_dir }}/templates/{{ kibana_conf_template }}"
    dest: /etc/kibana/kibana.yml
    owner: kibana
    group: kibana
  when: kibana_conf_template is defined
  notify: restart kibana
  
    
